#!/bin/bash
#
# GetMoreDone - Fix Wrong Project Credentials
#
# This script helps you create a NEW Google Cloud project for GetMoreDone
#

echo "================================================================"
echo "  Fix: Wrong Google Cloud Project"
echo "================================================================"
echo ""
echo "PROBLEM: Your credentials.json is from 'bowen1rag' project"
echo "SOLUTION: Create a new 'getmoredone' project"
echo ""
echo "Follow these steps:"
echo ""
echo "1. Go to: https://console.cloud.google.com/"
echo ""
echo "2. Click dropdown at top (next to 'Google Cloud')"
echo "   Click 'NEW PROJECT'"
echo ""
echo "3. Project name: getmoredone"
echo "   Click 'CREATE'"
echo ""
echo "4. Wait for project to be created, then select it"
echo ""
echo "5. Enable Google Calendar API:"
echo "   - Go to 'APIs & Services' > 'Library'"
echo "   - Search for 'Google Calendar API'"
echo "   - Click 'ENABLE'"
echo ""
echo "6. Configure OAuth consent screen:"
echo "   - Go to 'APIs & Services' > 'OAuth consent screen'"
echo "   - User Type: External (or Internal if G Workspace)"
echo "   - Click 'CREATE'"
echo "   - App name: GetMoreDone"
echo "   - User support email: YOUR_EMAIL"
echo "   - Developer contact: YOUR_EMAIL"
echo "   - Click 'SAVE AND CONTINUE'"
echo "   - Scopes: Click 'ADD OR REMOVE SCOPES'"
echo "     - Search for 'calendar'"
echo "     - Check: '.../auth/calendar'"
echo "     - Click 'UPDATE'"
echo "   - Click 'SAVE AND CONTINUE'"
echo "   - Test users: Click '+ ADD USERS'"
echo "     - Add YOUR_EMAIL"
echo "     - Click 'ADD'"
echo "   - Click 'SAVE AND CONTINUE'"
echo ""
echo "7. Create OAuth credentials:"
echo "   - Go to 'APIs & Services' > 'Credentials'"
echo "   - Click '+ CREATE CREDENTIALS' > 'OAuth client ID'"
echo "   - Application type: Desktop app"
echo "   - Name: GetMoreDone Desktop"
echo "   - Click 'CREATE'"
echo ""
echo "8. Download credentials:"
echo "   - Click the download icon (⬇️) next to your new OAuth 2.0 Client ID"
echo "   - Rename the file to: credentials.json"
echo "   - Move it to: ~/.getmoredone/credentials.json"
echo ""
echo "9. Run this command to replace the old credentials:"
echo "   mv ~/Downloads/client_secret_*.json ~/.getmoredone/credentials.json"
echo "   chmod 600 ~/.getmoredone/credentials.json"
echo ""
echo "10. Test authentication:"
echo "    python3 test_auth.py"
echo ""
echo "================================================================"
