"""
Obsidian integration utilities.
Handles note creation and opening notes in Obsidian.
"""

import os
import subprocess
import platform
from pathlib import Path
from datetime import datetime
from urllib.parse import quote


def _yaml_dq(value: str) -> str:
    """Escape a string for use inside a YAML double-quoted scalar.

    Backslash must be escaped before the quote. Without this, a title
    containing a double quote (e.g. Say "hi") would emit invalid YAML and
    break parsing of the entire frontmatter block.
    """
    return value.replace("\\", "\\\\").replace('"', '\\"')


def create_obsidian_note(
    vault_path: str,
    subfolder: str,
    entity_id: str,
    title: str,
    initial_content: str = "",
) -> str:
    """
    Create a new Obsidian note file.

    The note's frontmatter contains exactly these Obsidian properties, in this
    display order: Prev, Next, tags, title, entity_id, created, Summary.
    Prev/Next/tags are written empty (list/tags-typed in the vault); title,
    entity_id and created are populated; Summary is left for the user to fill in.

    Args:
        vault_path: Path to Obsidian vault
        subfolder: Subfolder within vault (e.g., "GetMoreDone")
        entity_id: ID of the linked entity (stored as the entity_id property)
        title: Title for the note
        initial_content: Optional initial markdown content (note body)

    Returns:
        Full file path to created note

    Raises:
        ValueError: If vault path doesn't exist
    """
    # Validate vault path
    vault = Path(vault_path)
    if not vault.exists():
        raise ValueError(f"Obsidian vault not found: {vault_path}")

    # Create subfolder if needed
    notes_folder = vault / subfolder
    notes_folder.mkdir(exist_ok=True)

    # Sanitize title for filename
    safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).strip()
    if not safe_title:
        safe_title = "untitled"

    # Generate filename: {Title} - yyyy-mm-dd.md
    date_str = datetime.now().strftime("%Y-%m-%d")
    filename = f"{safe_title} - {date_str}.md"
    file_path = notes_folder / filename

    # Handle duplicate filenames by appending a number
    counter = 1
    while file_path.exists():
        filename = f"{safe_title} - {date_str} ({counter}).md"
        file_path = notes_folder / filename
        counter += 1

    # Frontmatter — exactly the Obsidian properties the Notes-table export
    # defines, in display order. Prev/Next are empty (list-typed in the vault),
    # tags is empty (Obsidian tags), title/entity_id/created are populated, and
    # Summary is left empty for the user.
    frontmatter_lines = [
        "---",
        "Prev:",
        "Next:",
        "tags:",
        f'title: "{_yaml_dq(title)}"',
        f"entity_id: {entity_id}",
        f"created: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "Summary:",
        "---",
    ]
    frontmatter = "\n".join(frontmatter_lines)

    # Create note content
    note_content = f"""{frontmatter}

# {title}

{initial_content}
"""

    # Write file
    file_path.write_text(note_content, encoding='utf-8')

    return str(file_path)


def open_in_obsidian(file_path: str, vault_path: str):
    """
    Open a note file in Obsidian application.

    Uses Obsidian URI scheme (obsidian://open?...) for native integration.
    Falls back to system default app if Obsidian not available.

    Args:
        file_path: Full path to the markdown file
        vault_path: Path to Obsidian vault root

    Raises:
        ValueError: If file is not inside vault
    """
    file_path = Path(file_path)
    vault_path = Path(vault_path)

    # Get relative path from vault root (Obsidian needs this)
    try:
        relative_path = file_path.relative_to(vault_path)
    except ValueError:
        raise ValueError(f"Note file must be inside vault. File: {file_path}, Vault: {vault_path}")

    # Construct Obsidian URI
    # Format: obsidian://open?vault={vault_name}&file={relative_path}
    # Percent-encode both parts: note names generated by this app contain spaces
    # (e.g. "Title - 2026-01-01.md"), and a raw space makes the URI malformed, so
    # Obsidian activates but never opens the note. quote() keeps "/" in the path.
    vault_name = quote(vault_path.name, safe='')
    file_path_encoded = quote(str(relative_path).replace('\\', '/'), safe='/')
    obsidian_uri = f"obsidian://open?vault={vault_name}&file={file_path_encoded}"

    # Open URI based on platform
    system = platform.system()
    try:
        if system == "Darwin":  # macOS
            subprocess.call(['open', obsidian_uri])
        elif system == "Windows":
            os.startfile(obsidian_uri)
        elif system == "Linux":
            subprocess.call(['xdg-open', obsidian_uri])
    except Exception as e:
        # Fallback: open with system default app
        print(f"Could not open in Obsidian: {e}. Trying system default app...")
        open_with_default_app(str(file_path))


def open_with_default_app(file_path: str):
    """
    Open file with system default application.

    Fallback when Obsidian is not available.

    Args:
        file_path: Full path to the file
    """
    system = platform.system()
    try:
        if system == "Darwin":  # macOS
            subprocess.call(['open', file_path])
        elif system == "Windows":
            os.startfile(file_path)
        elif system == "Linux":
            subprocess.call(['xdg-open', file_path])
    except Exception as e:
        raise RuntimeError(f"Could not open file: {e}")


def validate_obsidian_setup(vault_path: str, subfolder: str) -> tuple[bool, str]:
    """
    Validate Obsidian vault configuration.

    Args:
        vault_path: Path to Obsidian vault
        subfolder: Subfolder within vault

    Returns:
        Tuple of (is_valid, message)
    """
    if not vault_path:
        return False, "Vault path not configured"

    vault = Path(vault_path)
    if not vault.exists():
        return False, f"Vault path does not exist: {vault_path}"

    if not vault.is_dir():
        return False, f"Vault path is not a directory: {vault_path}"

    # Check if .obsidian folder exists (indicates it's a real vault)
    obsidian_folder = vault / ".obsidian"
    if not obsidian_folder.exists():
        return False, f"Not a valid Obsidian vault (missing .obsidian folder): {vault_path}"

    # Try to create subfolder
    try:
        notes_folder = vault / subfolder
        notes_folder.mkdir(exist_ok=True)
    except Exception as e:
        return False, f"Cannot create notes subfolder: {e}"

    return True, "Vault configuration is valid"
