"""The celebration overlay: a brief, unearned-feeling surprise on top of the savor.

Purpose: RP-4.5 — fire a short visual/audible flourish after the savor step,
         on the ~20% of completions the protocol picks at random.
Spec:    docs/spec_2026-08-23_dopamine_reward_protocol.md#45-reward-sequence-on-done
Tests:   tests/test_reward_celebration.py

Everything here is non-blocking and cancellable. The celebration runs while the
completion-note dialog is already opening on top of it, and the window it draws
on is destroyed moments later by the completion flow — so every scheduled frame
is tracked and every frame re-checks that its canvas still exists. A background
animation that raises "invalid command name" into the user's face after they
finished a task would be a poor reward.

Drawn rather than shipped as images: a canvas costs nothing, has no packaging
story, and works identically in a frozen build. The one real asset is the
chime, generated by tools/generate_tada_wav.py.
"""

from __future__ import annotations

import logging
import random
import tkinter as tk
from pathlib import Path
from typing import Optional

from ..paths import resource_root
from ..theme import semantic_colors
from ..utils.audio_playback import play_audio_file_async, play_system_beep

logger = logging.getLogger(__name__)

# Wall-clock length of a celebration and the animation step. 1.5s is long enough
# to register and short enough that it is over before it is in the way.
CELEBRATION_MS = 1500
FRAME_MS = 50

CONFETTI_PIECES = 44
BALLOONS = ("🎈", "🎈", "🎉", "✨")
TADA_TEXT = "Ta-DA!"


def celebration_audio_path() -> Path:
    """Where the bundled chime lives, in source and frozen runs alike."""
    return resource_root() / "assets" / "audio" / "tada.wav"


class TimerCelebrationMixin:
    """Adds ``fire_celebration`` to the timer window."""

    def _celebration_state(self):
        """Lazily create the bookkeeping, so __init__ order cannot matter."""
        if not hasattr(self, "_celebration_after_ids"):
            self._celebration_after_ids = set()
            self._celebration_canvas = None
        return self._celebration_after_ids

    def _celebration_after(self, delay_ms: int, callback):
        """``after`` that remembers its id, so the whole thing can be cancelled."""
        pending = self._celebration_state()
        handle = None

        def run():
            pending.discard(handle)
            callback()

        handle = self.after(delay_ms, run)
        pending.add(handle)
        return handle

    def cancel_celebration(self):
        """Stop any celebration and tear down its canvas.

        Called from the timer's cleanup. Safe to call when nothing is running,
        when the window is already half destroyed, and twice in a row.
        """
        pending = self._celebration_state()
        for handle in list(pending):
            try:
                self.after_cancel(handle)
            except Exception:
                pass
        pending.clear()

        canvas = getattr(self, "_celebration_canvas", None)
        if canvas is not None:
            try:
                canvas.destroy()
            except Exception:
                pass
            self._celebration_canvas = None

    def fire_celebration(self, kind: Optional[str]) -> bool:
        """Run one celebration. Returns whether anything actually happened.

        Purpose: RP-4.5 — the surprise channel, always on top of the savor and
                 never instead of it.
        Tests:   tests/test_reward_celebration.py::test_rp45f_celebration_cleans_up_on_window_close

        A falsy ``kind`` is the ordinary case — the protocol decided not to
        celebrate — and returns False without drawing anything.
        """
        # Before the early return, not after: the bookkeeping is what
        # cancel_celebration reads, and on the common no-celebration path this
        # is the only call that ever creates it.
        self._celebration_state()

        if not kind:
            return False

        self.cancel_celebration()  # never stack two

        if kind == "tada":
            self._play_celebration_sound()

        canvas = self._build_celebration_canvas()
        if canvas is None:
            # No window to draw on. The sound, if any, has already played, so
            # say whether *something* happened rather than reporting failure.
            return kind == "tada"

        if kind == "confetti":
            self._animate_confetti(canvas)
        elif kind == "balloon":
            self._animate_balloons(canvas)
        elif kind == "tada":
            self._animate_tada(canvas)
        else:
            logger.warning("[reward_protocol] unknown celebration type %r", kind)
            self.cancel_celebration()
            return False

        self._celebration_after(CELEBRATION_MS, self.cancel_celebration)
        return True

    # -- the pieces ----------------------------------------------------------

    def _play_celebration_sound(self) -> bool:
        """The bundled chime, or the system sound, or nothing — but say which."""
        path = celebration_audio_path()
        if path.exists() and play_audio_file_async(str(path)):
            return True
        if not path.exists():
            logger.warning(
                "[reward_protocol] celebration chime missing at %s; using the system sound", path
            )
        else:
            logger.warning(
                "[reward_protocol] no audio player could open %s; using the system sound", path
            )
        return play_system_beep()

    def _build_celebration_canvas(self) -> Optional[tk.Canvas]:
        """An overlay canvas across the timer window, or None if there isn't one."""
        try:
            if not self.winfo_exists():
                return None
            palette = semantic_colors()
            canvas = tk.Canvas(
                self,
                highlightthickness=0,
                bd=0,
                bg=palette["surface"],
            )
            canvas.place(relx=0, rely=0, relwidth=1, relheight=1)
            canvas.update_idletasks()
            self._celebration_canvas = canvas
            return canvas
        except tk.TclError:
            return None

    def _canvas_size(self, canvas) -> tuple[int, int]:
        """Real size where the window is laid out, a sane guess where it is not.

        A withdrawn window reports 1x1, which would pile every piece of confetti
        into the top-left corner.
        """
        width = max(canvas.winfo_width(), 1)
        height = max(canvas.winfo_height(), 1)
        if width <= 1 or height <= 1:
            return 380, 520
        return width, height

    def _accent_colors(self) -> list[str]:
        """Celebration colours, from the theme rather than invented here."""
        palette = semantic_colors()
        return [
            palette["primary"],
            palette["warning"],
            palette["danger"],
            palette["success_strong"],
            palette["date_start_text"],
            palette["date_due_text"],
        ]

    def _animate_confetti(self, canvas):
        width, height = self._canvas_size(canvas)
        colors = self._accent_colors()
        # Visual jitter only. A module-level Random deliberately, not the
        # protocol's injected rng: how the confetti scatters must never consume
        # draws from the stream that decides the rewards.
        jitter = random.Random()

        pieces = []
        for _ in range(CONFETTI_PIECES):
            x = jitter.uniform(0, width)
            y = jitter.uniform(-height * 0.4, 0)
            size = jitter.uniform(4, 9)
            item = canvas.create_rectangle(
                x, y, x + size, y + size * 1.6,
                fill=jitter.choice(colors), outline="",
            )
            pieces.append((item, jitter.uniform(5, 13), jitter.uniform(-1.6, 1.6)))

        def step():
            if not self._still_running(canvas):
                return
            for item, fall, drift in pieces:
                canvas.move(item, drift, fall)
            self._celebration_after(FRAME_MS, step)

        self._celebration_after(FRAME_MS, step)

    def _animate_balloons(self, canvas):
        width, height = self._canvas_size(canvas)
        jitter = random.Random()

        floaters = []
        for index in range(len(BALLOONS) * 2):
            x = width * (index + 0.5) / (len(BALLOONS) * 2)
            item = canvas.create_text(
                x, height + jitter.uniform(0, height * 0.5),
                text=BALLOONS[index % len(BALLOONS)],
                font=("Helvetica", int(jitter.uniform(22, 38))),
            )
            floaters.append((item, jitter.uniform(6, 14), jitter.uniform(-1.0, 1.0)))

        def step():
            if not self._still_running(canvas):
                return
            for item, rise, sway in floaters:
                canvas.move(item, sway, -rise)
            self._celebration_after(FRAME_MS, step)

        self._celebration_after(FRAME_MS, step)

    def _animate_tada(self, canvas):
        width, height = self._canvas_size(canvas)
        palette = semantic_colors()
        item = canvas.create_text(
            width / 2, height / 2,
            text=TADA_TEXT,
            fill=palette["primary"],
            font=("Helvetica", 40, "bold"),
        )

        def step():
            if not self._still_running(canvas):
                return
            canvas.move(item, 0, -4)
            self._celebration_after(FRAME_MS, step)

        self._celebration_after(FRAME_MS, step)

    def _still_running(self, canvas) -> bool:
        """Has the window survived long enough for another frame?"""
        try:
            return bool(canvas.winfo_exists()) and self._celebration_canvas is canvas
        except tk.TclError:
            return False
